jobs:
  include:
    - os: windows
      language: shell
      script:
        - export PATH="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin":$PATH
        - MSBuild.exe
